function abrirAdmin(){const pin=prompt("Clave administrador:");if(pin!==ADMIN_PIN){if(pin!==null)alert("Clave incorrecta.");return}$("adminModal").classList.remove("hide");actualizarAdmin()}
function cerrarAdmin(){$("adminModal").classList.add("hide");$("seleccionBox").classList.add("hide");enfocarCodigo()}
function actualizarAdmin(){const d=datos();$("adminInfo").textContent=`Registros locales: ${d.length} | Pendientes sync: ${d.filter(r=>!r.sincronizado).length}`}
function recursoCSV(r){if(r.recurso)return r.recurso;if(r.estacion==="BALANZA"&&(r.tipo_mineral||r.tipoMineral))return String(r.tipo_mineral||r.tipoMineral).toUpperCase();if(r.estacion==="CANCHA"&&r.ubicacion)return String(r.ubicacion).toUpperCase();if(r.estacion==="DESCARGUIO"&&r.tolva)return"T"+r.tolva;if(r.estacion==="CHANCADO"&&r.circuito)return"C"+r.circuito;if(r.estacion==="SECADO"&&r.horno)return"H"+r.horno;if(r.estacion==="PULVERIZADO"&&r.molino)return"M"+r.molino;return""}
function exportarCSV(){const rows=[["CODIGO","EVENTO","FECHA_HORA","OPERADOR","ESTACION","RECURSO","ID"]];datos().forEach(r=>rows.push([r.codigo,r.evento,r.fecha_hora,r.operador,r.estacion,recursoCSV(r),r.id]));const csv="\ufeff"+rows.map(r=>r.map(c=>`"${String(c||"").replace(/"/g,'""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download="respaldo_kamban_"+Date.now()+".csv";a.click()}
function gruposFinalizadosAnteriores(diasMinimos=0){const grupos={};datos().filter(r=>!r.eliminado).forEach(r=>{const k=r.estacion+"||"+r.codigo;(grupos[k]||(grupos[k]=[])).push(r)});const ids=[];const limite=new Date();limite.setHours(0,0,0,0);limite.setDate(limite.getDate()-Number(diasMinimos||0));Object.values(grupos).forEach(regs=>{regs.sort((a,b)=>String(a.fecha_hora).localeCompare(String(b.fecha_hora)));const u=regs[regs.length-1],ev=String(u.evento||"").toUpperCase();const f=new Date(String(u.fecha_hora||"").replace(" ","T"));if((ev==="FINAL"||ev==="FINALIZADO")&&!isNaN(f)&&f<limite&&regs.every(r=>r.sincronizado))regs.forEach(r=>ids.push(r.id))});return ids}
function encolarBorrados(regs){const actuales=leerBorradosPendientes(),mapa=new Map(actuales.map(x=>[x.id,x]));regs.filter(r=>r.sincronizado).forEach(r=>mapa.set(r.id,{id:String(r.id),estacion:String(r.estacion||"").toUpperCase()}));guardarBorradosPendientes([...mapa.values()]);procesarBorradosPendientes(false)}
function borrarIdsEnLote(ids,avisar=true){const lote=ids.slice(0,BORRADO_LOTE_MAX);if(!lote.length)return 0;const before=datos(),regs=before.filter(r=>lote.includes(r.id));guardarDatos(before.filter(r=>!lote.includes(r.id)));encolarBorrados(regs);render();actualizarAdmin();if(avisar)alert(`Borrado local terminado: ${regs.length}. La eliminación remota se enviará en segundo plano cuando haya señal.${ids.length>lote.length?`\n\nQuedan ${ids.length-lote.length} registros por borrar.`:""}`);return regs.length}
async function borrarAnterioresFinalizados(){const ids=gruposFinalizadosAnteriores(0);if(!ids.length){alert("No hay códigos finalizados sincronizados de días anteriores.");return}const lote=ids.slice(0,BORRADO_LOTE_MAX);if(!confirm(`Hay ${ids.length} registros elegibles.\n\nSe borrarán máximo ${lote.length} en este bloque para evitar demoras.\n\n¿Continuar?`))return;await borrarIdsEnLote(ids,true)}
function limpiezaAutomaticaLocal(){const ids=gruposFinalizadosAnteriores(RETENCION_LOCAL_DIAS);if(!ids.length)return;borrarIdsEnLote(ids,false)}
function mostrarBorradoSeleccionados(){$("seleccionBox").classList.remove("hide");const rows=datos().map(r=>`<tr><td><input type="checkbox" class="selBorrar" value="${r.id}"></td><td>${r.codigo}</td><td>${r.evento}</td><td>${r.fecha_hora}</td><td>${r.estacion}</td><td>${recursoCSV(r)||"-"}</td><td>${r.sincronizado?"OK":"PEND"}</td></tr>`).join("");$("tablaSeleccion").innerHTML="<table><tr><th></th><th>Código</th><th>Evento</th><th>Fecha</th><th>Estación</th><th>Recurso</th><th>Sync</th></tr>"+rows+"</table>";$("seleccionBox").scrollIntoView({block:"start",behavior:"smooth"})}
function confirmarBorradoSeleccionados(){const ids=[...document.querySelectorAll(".selBorrar:checked")].map(x=>x.value);if(!ids.length){alert("Seleccione al menos un registro.");return}const lote=ids.slice(0,BORRADO_LOTE_MAX);if(!confirm(`Seleccionados: ${ids.length}.\nSe eliminarán máximo ${lote.length} en este bloque.\n\n¿Continuar?`))return;borrarIdsEnLote(lote,false);mostrarBorradoSeleccionados();alert(`Eliminados localmente: ${lote.length}. El envío remoto continuará en segundo plano.`)}
