function abrirAdmin(){const pin=prompt("Clave administrador:");if(pin!==ADMIN_PIN){if(pin!==null)alert("Clave incorrecta.");return}$("adminModal").classList.remove("hide");actualizarAdmin()}
function cerrarAdmin(){$("adminModal").classList.add("hide");$("seleccionBox").classList.add("hide");enfocarCodigo()}
function actualizarAdmin(){const d=datos();$("adminInfo").textContent=`Registros locales: ${d.length} | Pendientes sync: ${d.filter(r=>!r.sincronizado).length}`}
function recursoCSV(r){if(r.recurso)return r.recurso;if(r.estacion==="DESCARGUIO"&&r.tolva)return"T"+r.tolva;if(r.estacion==="CHANCADO"&&r.circuito)return"C"+r.circuito;if(r.estacion==="SECADO"&&r.horno)return"H"+r.horno;if(r.estacion==="PULVERIZADO"&&r.molino)return"M"+r.molino;return""}
function exportarCSV(){const rows=[["CODIGO","EVENTO","FECHA_HORA","OPERADOR","ESTACION","RECURSO","ID"]];datos().forEach(r=>rows.push([r.codigo,r.evento,r.fecha_hora,r.operador,r.estacion,recursoCSV(r),r.id]));const csv="\ufeff"+rows.map(r=>r.map(c=>`"${String(c||"").replace(/"/g,'""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download="respaldo_kamban_"+Date.now()+".csv";a.click()}
function gruposFinalizadosAnteriores(){const grupos={};datos().filter(r=>!r.eliminado).forEach(r=>{const k=r.estacion+"||"+r.codigo;(grupos[k]||(grupos[k]=[])).push(r)});const ids=[];Object.values(grupos).forEach(regs=>{regs.sort((a,b)=>String(a.fecha_hora).localeCompare(String(b.fecha_hora)));const u=regs[regs.length-1],ev=String(u.evento||"").toUpperCase();if((ev==="FINAL"||ev==="FINALIZADO")&&fechaSolo(u.fecha_hora)<hoyISO())regs.forEach(r=>ids.push(r.id))});return ids}
async function enviarBorradoRemoto(regs){const url=endpoint();if(!url||!navigator.onLine)return;for(const r of regs.filter(x=>x.sincronizado)){try{await fetch(url,{method:"POST",mode:"no-cors",headers:{"Content-Type":"application/json"},body:JSON.stringify({...r,eliminado:true})})}catch(e){}}}
async function borrarAnterioresFinalizados(){const ids=gruposFinalizadosAnteriores();if(!ids.length){alert("No hay códigos finalizados de días anteriores.");return}if(!confirm(`Se eliminarán ${ids.length} registros de códigos finalizados antes de hoy.\n\nSe conservarán pendientes y finalizados de hoy.\n\n¿Continuar?`))return;const before=datos(),regs=before.filter(r=>ids.includes(r.id));await enviarBorradoRemoto(regs);guardarDatos(before.filter(r=>!ids.includes(r.id)));render();actualizarAdmin();alert("Borrado terminado. Eliminados: "+regs.length)}
function mostrarBorradoSeleccionados(){$("seleccionBox").classList.remove("hide");const rows=datos().map(r=>`<tr><td><input type="checkbox" class="selBorrar" value="${r.id}"></td><td>${r.codigo}</td><td>${r.evento}</td><td>${r.fecha_hora}</td><td>${r.estacion}</td><td>${recursoCSV(r)||"-"}</td><td>${r.sincronizado?"OK":"PEND"}</td></tr>`).join("");$("tablaSeleccion").innerHTML="<table><tr><th></th><th>Código</th><th>Evento</th><th>Fecha</th><th>Estación</th><th>Recurso</th><th>Sync</th></tr>"+rows+"</table>"}
async function confirmarBorradoSeleccionados(){const ids=[...document.querySelectorAll(".selBorrar:checked")].map(x=>x.value);if(!ids.length){alert("Seleccione al menos un registro.");return}if(!confirm("¿Eliminar los registros seleccionados?"))return;const before=datos(),regs=before.filter(r=>ids.includes(r.id));await enviarBorradoRemoto(regs);guardarDatos(before.filter(r=>!ids.includes(r.id)));render();actualizarAdmin();mostrarBorradoSeleccionados();alert("Eliminados: "+regs.length)}
