const APP_VERSION="0002.7.2";
const DB_KEY="kamban_acopio_db_v0001";
const DB_BACKUP_KEY="kamban_acopio_db_respaldo_v0001";
const LAST_SYNC_KEY="kamban_ultima_sync_v0001";
const LAST_TURN_CLEAR_KEY="kamban_turno_v0001";
const ADMIN_PIN="1234";
const AUTO_REGISTER_DELAY_MS=550;
const ENDPOINT_FIJO="https://script.google.com/macros/s/AKfycbxSU5AteIl0u7FoOCeLNssQEVWvEvNssTGwkKZ4-vDSHUKeV64HXJdIH0NKs2u_HdQ/exec";
const BACKEND_VERSION_ESPERADA="0002.7.0";

const STATIONS=[
  "BALANZA","DESCARGUIO","CHANCADO","MUESTREO",
  "SECADO","PULVERIZADO","CUARTEOSELLADO","ATENCION AL CLIENTE"
];

const EVENTS_BY_STATION={
  "BALANZA":["INICIO"],
  "DESCARGUIO":["INICIO","FINAL"],
  "CHANCADO":["INICIO","FINAL"],
  "ATENCION AL CLIENTE":["FINAL"],
  "DEFAULT":["RECEPCION","INICIO","FINAL"]
};

const UMBRALES_MINUTOS={
  "BALANZA":30,"DESCARGUIO":60,"CHANCADO":45,"MUESTREO":45,
  "SECADO":180,"PULVERIZADO":90,"CUARTEOSELLADO":45,
  "ATENCION AL CLIENTE":60
};



const SYNC_REQUEST_TIMEOUT_MS=20000;
const SYNC_RETRY_BASE_MS=2000;
const SYNC_RETRY_MAX_MS=30000;
const SYNC_PERIODIC_MS=10000;
