const APP_VERSION = "2.000 CR";
const DB_KEY = "kamban_acopio_db_v2";
const LAST_SYNC_KEY = "kamban_ultima_sync_v2";
const LAST_TURN_CLEAR_KEY = "kamban_turno_v2";
const ADMIN_PIN = "1234";
const AUTO_REGISTER_DELAY_MS = 550;

// URL de Apps Script actual:
const ENDPOINT_FIJO = "https://script.google.com/macros/s/AKfycbyePuatXW66C2ZnPz1Y1RnpzMEiEj-8Omh_Xqa09l9dgt6ZUR2zi-a08P1gZCAA1k0A/exec";

const STATIONS = ["BALANZA","DESCARGUIO","CHANCADO","MUESTREO","SECADO","PULVERIZADO","CUARTEOSELLADO","ATENCION AL CLIENTE"];
const EVENTS_BY_STATION = {
  "BALANZA": ["INICIO"],
  "DESCARGUIO": ["INICIO","FINAL"],
  "CHANCADO": ["INICIO","FINAL"],
  "ATENCION AL CLIENTE": ["FINAL"],
  "DEFAULT": ["RECEPCION","INICIO","FINAL"]
};
const UMBRALES_MINUTOS = {
  "BALANZA": 30, "DESCARGUIO": 60, "CHANCADO": 45, "MUESTREO": 45,
  "SECADO": 180, "PULVERIZADO": 90, "CUARTEOSELLADO": 45, "ATENCION AL CLIENTE": 60
};
